imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    secret:        %secret%
    charset:       UTF-8
    csrf_protection:
        enabled: true
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:
        enabled: true
        enable_annotations: true
    form:
        enabled: true
    templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        lifetime:       72000
        auto_start:     true

sensio_framework_extra:
    router:  { annotations: true }
    request: { converters: true }
    view:    { annotations: true }
    cache:   { annotations: true }

        
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources: [IHQSNuitBlancheBundle::form.html.twig]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        options:
            # enforce PDO::MYSQL_ATTR_USE_BUFFERED_QUERY to true
            1000: true  

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            IHQSNuitBlancheBundle: { type: annotation, dir: Entity/ }
            IHQSForumBundle: { type: annotation, dir: Entity/ }

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# Admin Configuration
white_october_admin:
    data_managers:
        doctrine:
            orm:    true
            odm:    false
        mandango:   false
    admins:
        - { class: IHQS\NuitBlancheBundle\Admin\NewsAdmin }
        - { class: IHQS\NuitBlancheBundle\Admin\UserAdmin }
        - { class: IHQS\NuitBlancheBundle\Admin\WarAdmin }

ihqs_nuit_blanche: ~

ihqs_forum: ~

ihqs_wysiwyg:
    selector: wysiwyg_editor
    editor:
        library: ckeditor
        set: custom
        theme: kama

forum:
    db_driver: orm
    class:
        model:
            category: IHQS\ForumBundle\Entity\Category
            topic: IHQS\ForumBundle\Entity\Topic
            post: IHQS\ForumBundle\Entity\Post
        blamer:
            post: IHQS\ForumBundle\Blamer\PostBlamer
    paginator:
        topics_per_page: 10
        posts_per_page: 10
        search_results_per_page: 10