ihqs_forum:
    resource: "@IHQSForumBundle/Resources/config/routing.yml"
    prefix:     /forum

ihqs_nuitblanche:
    resource: "@IHQSNuitBlancheBundle/Resources/config/routing.yml"

ihqs_tournament:
    resource: "@IHQSTournamentBundle/Resources/config/routing.yml"
    prefix:     /tournament

forum:
    resource: "@ForumBundle/Resources/config/routing/forum.xml"
    prefix:     /forum

forum_category:
    resource: "@ForumBundle/Resources/config/routing/category.xml"
    prefix:     /forum
    
forum_topic:
    resource: "@ForumBundle/Resources/config/routing/topic.xml"
    prefix:     /forum

forum_post:
    resource: "@ForumBundle/Resources/config/routing/post.xml"
    prefix:     /forum
