main:
    resource: "@IHQSNuitBlancheBundle/Controller/MainController.php"
    type:     annotation

league:
    resource: "@IHQSNuitBlancheBundle/Controller/LeagueController.php"
    type:     annotation

news:
    resource: "@IHQSNuitBlancheBundle/Controller/NewsController.php"
    type:     annotation

player:
    resource: "@IHQSNuitBlancheBundle/Controller/PlayerController.php"
    type:     annotation

replay:
    resource: "@IHQSNuitBlancheBundle/Controller/ReplayController.php"
    type:     annotation

stream:
    resource: "@IHQSNuitBlancheBundle/Controller/StreamController.php"
    type:     annotation

ts3:
    resource: "@IHQSNuitBlancheBundle/Controller/Ts3Controller.php"
    type:     annotation

team:
    resource: "@IHQSNuitBlancheBundle/Controller/TeamController.php"
    type:     annotation

war:
    resource: "@IHQSNuitBlancheBundle/Controller/WarController.php"
    type:     annotation

secured:
    resource: "@IHQSNuitBlancheBundle/Controller/SecuredController.php"
    type:     annotation

forum:
    resource: "@ForumBundle/Resources/config/routing/forum.xml"
    prefix:     /forum

forum_category:
    resource: "@ForumBundle/Resources/config/routing/category.xml"
    prefix:     /forum
    
forum_topic:
    resource: "@ForumBundle/Resources/config/routing/topic.xml"
    prefix:     /forum

forum_post:
    resource: "@ForumBundle/Resources/config/routing/post.xml"
    prefix:     /forum
    
_white_october_admin:
    resource: .
    type: white_october_admin

white_october_admin:
    resource: "@WhiteOctoberAdminBundle/Resources/config/routing/admin.xml"
    prefix:   /admin