security:
    encoders:
        IHQS\NuitBlancheBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_MEMBER:      ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_MEMBER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_MEMBER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: IHQS\NuitBlancheBundle\Entity\User, property: username }
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false

        login:
            pattern:  ^/login$
            security: false

        main:
            pattern:    /.*
            form_login:
                check_path:   /login_check
                login_path:   /
                use_referer:  true
            logout:
                path:   /logout
                target: /
            anonymous: ~

    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /contribute/.*, roles: ROLE_MEMBER }
        - { path: /forum/.*, roles: ROLE_MEMBER }
