<?php

namespace IHQS\NuitBlancheBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function findLast()
    {
        list($news) = $this->createQueryBuilder('n')->
            orderBy('n.date', 'DESC')->
            setMaxResults(1)->
            getQuery()->
            execute();

        return $news;
    }

    public function findLatest()
    {
        return $this->createQueryBuilder('n')->
            orderBy('n.date', 'DESC')->
            setMaxResults(5)->
            getQuery()->
            execute();
    }
}