<?php

namespace IHQS\NuitBlancheBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function loadUserByUsername($username)
    {
        // do whatever you need to retrieve the user from the database
        // code below is the implementation used when using the property setting

        return $this->findOneBy(array('username' => $username));
    }
}