<?php

namespace IHQS\NuitBlancheBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * WarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarRepository extends EntityRepository
{
    public function findLatest()
    {
        return $this->createQueryBuilder('w')->
            orderBy('w.date', 'DESC')->
            setMaxResults(5)->
            getQuery()->
            execute();
    }
}